# -*- coding: utf-8 -*-
"""automate_preprocessing-NisaNuraini.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iyaRWqhpweYwHonLXXC5LF4UTV8SGVMD
"""

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from joblib import dump
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split
import pandas as pd

def preprocess_data(data, target_column, save_path, file_path):
    # menentukan fitur numerik dan kategoris
    num_features = data.select_dtypes(include=['float64', 'int64']).columns.tolist()
    cat_feature = data.select_dtypes(include=['object']).columns.tolist()
    column_names = data.columns
    # mendapatkan nama kolom tanpa kolom target
    column_names = data.columns.drop(target_column)

    # membuat dataframe kosong dengan nama kolom
    df_header = pd.DataFrame(columns=column_names)

    # menyimpan nama kolom sebagai header tanpa data
    df_header.to_csv(file_path, index=False)
    print(f"Nama kolom berhasil disimpan ke: {file_path}")

    # pastikan target_column tidak ada di num_feature atau cat_feature
    if target_column in num_features:
        num_features.remove(target_column)
    if target_column in cat_feature:
        cat_feature.remove(target_column)

    # pipeline untuk fitur numerik
    numeric_transformer = Pipeline(steps=[
        ('scaler', MinMaxScaler())
    ])

    # pipeline untuk fitur kategori
    categorical_transformer = Pipeline(steps=[
        ('encoder', LabelEncoder())
    ])

    # column transformer
    preprocessor = ColumnTransformer(
        transformers=[
            ('num', numeric_transformer, num_features),
            ('cat', categorical_transformer, cat_feature)
        ]
    )

    # memisahkan target
    X = data.drop(columns=[target_column])
    y = data[target_column]

    # membagi data
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # fitting dan transformasi data pada training set
    X_train = preprocessor.fit_transform(X_train)
    # transformasi data pada testing set
    X_test = preprocessor.transform(X_test)
    # simpan pipeline
    dump(preprocessor, save_path)

    return X_train, X_test, y_train, y_test